version: '3'

services:
  mysql_database:
    image: mysql
    container_name: mysql_database
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    expose:
      - '3306'
    volumes:
      - ./database:/var/lib/mysql
    
  web:
    build: ./app
    ports:
      - "5000:8888"
    links:
      - mysql_database
    volumes:
      - ./app:/app
    restart: on-failure

  # nginx:
  #   build: ./static
  #   volumes:
  #     - .:/code
  #   ports:
  #       - 80:80
    
  zigbee:
    build: ./zigbee
    ports:
      - "8001"
    links:
      - mysql_database
      
  